### ISSUE TITLE
Move window don't work in Debian

### ISSUE THREAD

**Issue by KingTimer12** [manga-you-know/desktop#2]
Hey, buddy! Basically, screen movement and resizing don't work. I'll take a look at that, maybe there's some missing permission from Tauri.

[Gravação de tela de 2024-10-14 15-41-58.webm](https://github.com/user-attachments/assets/07aceba2-d314-43de-9306-2be98eadd86b)

**Comment by KingTimer12** [comment]
I did some research and it seems to be a problem in Tauri itself. There is a solution I know of which is to create a component for decoration, for some reason, this even solves the resize problem. I have used this solution in other projects...

Issue about the problem: https://github.com/tauri-apps/tauri/issues/10686

**Comment by ReiLoko4** [comment]
yeah, the decorators are from tauri itself, I do want to create a custom decorate in the future but it isn't one of my priorities for now
